const tarifas={reel:{edicion:18000,produccion:28000,integral:35000},carrusel:{edicion:15000,produccion:22000,integral:28000},historias:{edicion:10000,produccion:15000,integral:18000}};
const descuentos={1:1,2:.95,3:.92,4:.90,5:.88,6:.85,7:.83,8:.80,9:.78,10:.75};
const porcentaje={1:0,2:5,3:8,4:10,5:12,6:15,7:17,8:20,9:22,10:25};
const nTrabajo={reel:"Reel",carrusel:"Carrusel",historias:"Pack Historias (Hasta 5)"};
const nTipo={edicion:"Edición solamente",produccion:"Producción y Grabación + Edición",integral:"Idea y Guión + Producción y Grabación + Edición"};
const items=[];const $=id=>document.getElementById(id);const dinero=n=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(Math.round(n));
function calc(i){return tarifas[i.trabajo][i.tipo]*i.cantidad*descuentos[i.cantidad]}
$("descuentosAccordion").querySelector(".accordion-header").onclick=()=>$("descuentosAccordion").classList.toggle("active");
function render(){let t=0,r=0,c=0,h=0;if(!items.length){$("lista").innerHTML='<div class="empty">Todavía no agregaste trabajos.</div>';$("total").textContent=$("reels").textContent=$("carruseles").textContent=$("historias").textContent=dinero(0);return}
$("lista").innerHTML=items.map((i,idx)=>{i.total=calc(i);t+=i.total;if(i.trabajo=="reel")r+=i.total;if(i.trabajo=="carrusel")c+=i.total;if(i.trabajo=="historias")h+=i.total;return `<div class="item"><div><strong>${i.cantidad} ${nTrabajo[i.trabajo]}</strong><br><small>${nTipo[i.tipo]}</small>${i.cantidad>1?`<span class="discount-tag">✓ Descuento aplicado: ${porcentaje[i.cantidad]}%</span>`:""}</div><div class="item-right"><strong>${dinero(i.total)}</strong><button class="delete-btn" onclick="eliminarItem(${idx})">🗑</button></div></div>`}).join("");$("total").textContent=dinero(t);$("reels").textContent=dinero(r);$("carruseles").textContent=dinero(c);$("historias").textContent=dinero(h)}
window.eliminarItem=i=>{items.splice(i,1);render()}
$("agregar").onclick=()=>{const trabajo=$("trabajo").value,tipo=$("tipo").value;if(!trabajo||!tipo){alert("Completá el trabajo y el tipo.");return}let cantidad=Math.max(1,Math.min(10,+$("cantidad").value||1));let ex=items.find(x=>x.trabajo==trabajo&&x.tipo==tipo);if(ex)ex.cantidad=Math.min(10,ex.cantidad+cantidad);else items.push({trabajo,tipo,cantidad});$("trabajo").selectedIndex=0;$("tipo").selectedIndex=0;$("cantidad").value=1;render()}
$("reiniciar").onclick=()=>{items.length=0;render()}
$("copiar").onclick=()=>{let s=0;const txt=items.map(i=>{i.total=calc(i);s+=i.total;return`${i.cantidad} ${nTrabajo[i.trabajo]} — ${nTipo[i.tipo]}: ${dinero(i.total)}`}).join("\n")+`\n\nTOTAL DEL PROYECTO: ${dinero(s)}`;navigator.clipboard.writeText(txt)}
$("pdf").onclick=()=>{if(!items.length)return;const {jsPDF}=window.jspdf,doc=new jsPDF();let y=24,s=0;doc.setFont("helvetica","bold");doc.setFontSize(20);doc.setTextColor(159,73,164);doc.text("Merlina Aguel",20,y);y+=8;doc.setFont("helvetica","normal");doc.setFontSize(12);doc.setTextColor(40);doc.text("Producción y Edición de Contenido",20,y);y+=10;doc.setFontSize(10);doc.setTextColor(120);doc.text("Fecha: "+new Date().toLocaleDateString("es-AR"),20,y);y+=12;doc.line(20,y,190,y);y+=10;items.forEach(i=>{i.total=calc(i);s+=i.total;doc.setFont("helvetica","bold");doc.text(`${i.cantidad} ${nTrabajo[i.trabajo]}`,20,y);y+=6;doc.setFont("helvetica","normal");doc.text(nTipo[i.tipo],20,y);doc.text(dinero(i.total),190,y,{align:"right"});y+=10;if(y>260){doc.addPage();y=20}});doc.line(20,y,190,y);y+=12;doc.setFont("helvetica","bold");doc.setFontSize(18);doc.setTextColor(159,73,164);doc.text("Total del proyecto",20,y);doc.text(dinero(s),190,y,{align:"right"});y+=18;doc.setFont("helvetica","normal");doc.setFontSize(10);doc.setTextColor(120);doc.text("Este presupuesto es orientativo y puede ajustarse según el alcance del proyecto.",20,y,{maxWidth:170});doc.save("Presupuesto-Merlina-Aguel.pdf")}
render();
